CREATE TABLE IF NOT EXISTS USERS (
    id SERIAl PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SESSIONS (
    id SERIAL PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUIZES (
    id SERIAL PRIMARY KEY, 
    title TEXT NOT NULL,
    description TEXT,
    points INT UNSIGNED NOT NULL DEFAULT 100,
    owner_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
  id SERIAL PRIMARY KEY,
  question TEXT NOT NULL,
  multiple_answers BOOLEAN NOT NULL DEFAULT 0,
  duration INT UNSIGNED NOT NULL DEFAULT 30
);

CREATE TABLE IF NOT EXISTS QUIZ_QUESTIONS (
    id SERIAL PRIMARY KEY, 
    quiz_id BIGINT UNSIGNED, 
    question_id BIGINT UNSIGNED,
    FOREIGN KEY (quiz_id) REFERENCES QUIZES(id) ON DELETE CASCADE, 
    FOREIGN KEY (question_id) REFERENCES QUESTIONS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ANSWERS (
    id SERIAL PRIMARY KEY,
    question_id BIGINT UNSIGNED NOT NULL,
    answer TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    FOREIGN KEY (question_id) REFERENCES QUESTIONS(id) ON DELETE CASCADE
);